"""
Demo defaults — precomputed results for instant cold-start on the canonical
configuration. Saves ~5–15s on the first page hit by skipping the 4-scenario
simulator entirely when the user's state matches the demo signature.

The signature is the tuple of every config knob that materially changes
simulation output. If any field differs, the precompute is ignored and the
live simulator runs as before.

Pickle artifacts live in ``data/precomputed/`` and are generated by
``scripts/precompute_demo_defaults.py``. The manifest records the exact
configuration the artifacts were generated with so we can detect mismatches
(schema drift, dataclass changes, stale data window) and fall back to live
recompute gracefully.
"""

from __future__ import annotations

import gzip
import json
import pickle
from dataclasses import asdict
from pathlib import Path
from typing import Any, Optional, Tuple

# Bump this when the SimulationResult dataclass shape changes — it invalidates
# every existing pickle and forces a regenerate via the precompute script.
SIMULATION_RESULT_VERSION = 1

PRECOMPUTE_DIR = Path(__file__).parent.parent / 'data' / 'precomputed'
SIM_PICKLE_PATH = PRECOMPUTE_DIR / 'sim_default.pkl.gz'
SWEEP_PICKLE_PATH = PRECOMPUTE_DIR / 'sweep_default.pkl.gz'
STRATEGY_PICKLE_PATH = PRECOMPUTE_DIR / 'strategy_default.pkl.gz'
NODAL_PICKLE_PATH = PRECOMPUTE_DIR / 'nodal_default.pkl.gz'
MANIFEST_PATH = PRECOMPUTE_DIR / 'manifest.json'


def state_signature(state: Any) -> Tuple:
    """Build the signature tuple for the current AppState.

    Order matters and must match the order used by the precompute script's
    manifest. Float fields are rounded to 6 decimals to absorb display rounding.
    """
    specs = state.battery_specs
    if specs is None:
        return tuple()  # not yet initialized → cannot match

    def r(x: float) -> float:
        return round(float(x), 6)

    return (
        state.selected_node,
        str(state.start_date),
        str(state.end_date),
        r(specs.capacity_mwh),
        r(specs.power_mw),
        r(specs.efficiency),
        r(specs.min_soc),
        r(specs.max_soc),
        r(specs.initial_soc),
        state.strategy_type,
        int(state.horizon_hours),
        int(state.window_hours),
        r(state.charge_percentile),
        r(state.discharge_percentile),
        r(state.forecast_improvement),
    )


def _load_manifest() -> Optional[dict]:
    if not MANIFEST_PATH.exists():
        return None
    try:
        with open(MANIFEST_PATH, encoding='utf-8') as f:
            return json.load(f)
    except (OSError, json.JSONDecodeError):
        return None


def current_state_matches_demo(state: Any) -> bool:
    """Return True iff the live state signature matches the manifest exactly."""
    from config.settings import PRECOMPUTE_ENABLED  # local import: avoid cycles

    if not PRECOMPUTE_ENABLED:
        return False

    manifest = _load_manifest()
    if manifest is None:
        return False

    if manifest.get('simulation_result_version') != SIMULATION_RESULT_VERSION:
        return False

    expected = tuple(manifest.get('signature', []))
    actual = state_signature(state)
    return bool(expected) and expected == actual


def load_precomputed_simulations() -> Optional[dict]:
    """Return {scenario_name: SimulationResult} from the gzip'd pickle.

    Returns None on any failure so the caller can fall back to live recompute.
    """
    if not SIM_PICKLE_PATH.exists():
        return None
    try:
        with gzip.open(SIM_PICKLE_PATH, 'rb') as f:
            obj = pickle.load(f)
        if not isinstance(obj, dict):
            return None
        return obj
    except (OSError, pickle.UnpicklingError, EOFError, AttributeError, ModuleNotFoundError):
        return None


def load_precomputed_sweep() -> Optional[Tuple[dict, list]]:
    """Return (results_cache, history_data) for the Asset Design sweep, or None."""
    if not SWEEP_PICKLE_PATH.exists():
        return None
    try:
        with gzip.open(SWEEP_PICKLE_PATH, 'rb') as f:
            obj = pickle.load(f)
        if not (isinstance(obj, tuple) and len(obj) == 2):
            return None
        results_cache, history_data = obj
        if not (isinstance(results_cache, dict) and isinstance(history_data, list)):
            return None
        return results_cache, history_data
    except (OSError, pickle.UnpicklingError, EOFError, AttributeError, ModuleNotFoundError):
        return None


def load_precomputed_strategy_analysis() -> Optional[dict]:
    """Return precomputed Strategy Analysis sensitivity dict, or None.

    Expected shape:
        {
          'sensitivity': {
            'improvement_range': list[int],
            'revenue_threshold': list[float],
            'revenue_rolling_window': list[float],
            'revenue_mpc': list[float],
            'revenue_linear': list[float],
          },
          'horizon_sensitivity': {
            'horizon_range': list[int],
            'revenue_horizon': list[float],
          },
        }
    """
    if not STRATEGY_PICKLE_PATH.exists():
        return None
    try:
        with gzip.open(STRATEGY_PICKLE_PATH, 'rb') as f:
            obj = pickle.load(f)
        if not isinstance(obj, dict):
            return None
        return obj
    except (OSError, pickle.UnpicklingError, EOFError, AttributeError, ModuleNotFoundError):
        return None


def load_precomputed_nodal_analysis() -> Optional[Tuple]:
    """Return (results_df, node_data_cache) for the Nodal Analysis page, or None."""
    if not NODAL_PICKLE_PATH.exists():
        return None
    try:
        with gzip.open(NODAL_PICKLE_PATH, 'rb') as f:
            obj = pickle.load(f)
        if not (isinstance(obj, tuple) and len(obj) == 2):
            return None
        return obj
    except (OSError, pickle.UnpicklingError, EOFError, AttributeError, ModuleNotFoundError):
        return None


def write_manifest(signature: Tuple, extra: Optional[dict] = None) -> None:
    """Used by the precompute script to record what config was baked in."""
    PRECOMPUTE_DIR.mkdir(parents=True, exist_ok=True)
    payload = {
        'simulation_result_version': SIMULATION_RESULT_VERSION,
        'signature': list(signature),
        'signature_fields': [
            'selected_node', 'start_date', 'end_date',
            'capacity_mwh', 'power_mw', 'efficiency',
            'min_soc', 'max_soc', 'initial_soc',
            'strategy_type', 'horizon_hours', 'window_hours',
            'charge_percentile', 'discharge_percentile', 'forecast_improvement',
        ],
        **(extra or {}),
    }
    with open(MANIFEST_PATH, 'w', encoding='utf-8') as f:
        json.dump(payload, f, indent=2, default=str)
